[package]
name = "magic-wormhole-io-blocking"
version = "0.0.1"
authors = ["Brian Warner <warner@lothar.com>"]

[dependencies]
magic-wormhole-core = { path = "../../core" }
ws = "0.7.*"
url = "1.7"
serde_json = "1.0"
hex = "0.3"
jni = "0.10.2"

[lib]
crate-type = ["dylib"]

